### ISSUE TITLE
Plugin assumes resources will exist without checking.

### ISSUE THREAD

**Issue by johnd-itison** [rubiojr/knife-brightbox#21]
In 'delete' the plugin wants to display the image name:

https://github.com/rubiojr/knife-brightbox/blob/master/lib/chef/knife/brightbox_server_delete.rb#L75

However, an instance can be running with a deleted image, which means that `server.image` is nil and `server.image.name` causes the plugin to throw an exception.

The plugin should check resources exist before calling methods on them - the same's probably true for `flavor` there, too.

There's an existing check in `brightbox_server_list`, which is, I think, the only other place this bug could be run into?

https://github.com/rubiojr/knife-brightbox/blob/master/lib/chef/knife/brightbox_server_list.rb#L45

**Comment by tokengeek** [comment]
Thanks for reporting. I'll try to have a look today.

**Comment by tokengeek** [comment]
I've investigated this for a few hours and checked the support ticket, and the issue isn't that the images are "deleted". Deleted images are still available via the API and so I couldn't recreate this issue for a few hours.

Turns out the images have been made `private` again when they were once `public`. So the API is denying access.

So first API call to `srv-12345` is getting the nested information for `img-12345` which would be available as `server.image_id` but the call to `server.image` is making a second API call but is unable to load it, hence being nil.

So I'm going to guard against nil here but we'll also update the process for retiring official images since they should still be available.

We need the guard however in case a non official "public" image is used and the account owner makes it private later.

**Comment by johnd-itison** [comment]
Thanks for looking into this again - seems like a weird little edge case I've stumbled across!

**Comment by tokengeek** [comment]
Fix as part of v0.9.0

**Comment by johnd-itison** [comment]
Thank you! Have a kitten as appreciation:

![A random thank-you kitten!](https://cloud.githubusercontent.com/assets/6641252/7959783/e18ddf04-09f3-11e5-8f70-9a08fe3eabd0.jpg)
